#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DynamicUI.Resource", IsApplication=true)]

namespace DynamicUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int canola = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chemicals_toolshed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chemicalshed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int day = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int defaultshed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int farm = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int favourites = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int fertilise_toolshed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fuel_level = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int grain_level = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int news = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rain_gauge = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int settings = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int showers = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int toolshed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int userinfo = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int imgImage = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int linLayFT = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout6 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tableLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int tableRow1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int tableRow2 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int tableRow3 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int tableRow4 = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int txtText = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FTImageButton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
